### ISSUE TITLE
Fails during installation

### ISSUE THREAD

**Issue by ErenBalatkan** [ai-ku/Morse.jl#1]
Im getting following error during installation,
![image](https://user-images.githubusercontent.com/17107724/52864309-efadda80-314a-11e9-8df1-7403d14621e4.png)

This happens regardless of whether i use 
`add https://github.com/ai-ku/Morse.jl`
or
`dev https://github.com/ai-ku/Morse.jl`

**Comment by ekinakyurek** [comment]
Currently, I suggest to use git clone option for replicating and using
experiments.

**Comment by ErenBalatkan** [comment]
Thanks, works without issues that way

**Comment by ekinakyurek** [comment]
Since I strictly free package versions by Manifest.toml, add and dev
options will likely cause problems. I will resolve this after finalizing
package. However, by using activate ., you will use local environment and
versions will conform Manifest.toml. You will get exact same environment
that we use.

Best,
Ekin

**Comment by ekinakyurek** [comment]
strictly pin*

**Comment by ekinakyurek** [comment]
I keep open this issue, until it resolves. @Navhkrin if you have more questions/issues about setup please let me know

**Comment by denizyuret** [comment]
@ekinakyurek given that the current master works without Manifest.toml and with the latest julia / package versions, can we close this issue?
